export const CHANGE_SHOWTIP = 'CHANGE_SHOWTIP'

export const CHANGE_ISLOAD = 'CHANGE_ISLOAD'

export const CHANGE_ROTATEDEG = 'CHANGE_ROTATEDEG'

export const CHANGE_KEYWORDS = 'CHANGE_KEYWORDS'

export const CHANGE_SEARCHTYPE = 'CHANGE_SEARCHTYPE'

export const GETSEARCH80S = 'GETSEARCH80S'

export const GETSEARCHHF = 'GETSEARCHHF'

export const GETSEARCHDT = 'GETSEARCHDT'

export const INIT_SEARCHDATA = 'INIT_SEARCHDATA'

export const GETDETAIL80S = 'GETDETAIL80S'

export const GETDETAILHF = 'GETDETAILHF'
